# LigeroSmart OnPremise
#
# Enviroment variables description
#
# PROJECT_NAME 
#    Name for default stack used on elasticsearch index preffix
# 
# WEBSERVER_FQDN
#    DNS resolved name for application access. It's is used on FQDN system reference, 
#    to internal URL format, also to SSL keys auto creation if Letsencript support is enabled
# 
# URL Packages
# Ref.: https://download.znuny.org/releases/itsm/packages6/
#
# Hosts tags
# webserver = true
# database = true
# elasticsearch = true
# grafana = true


version: '3.8'

services:
  webserver:
    image: ligero/znuny:latest
    command: supervisord
    volumes:
      - app-data:/opt/otrs
      - app-backups:/app-backups
      - www-html:/var/www/html
    environment:
      - APP_DatabaseType=mysql
      - APP_DatabaseHost=database
      - APP_Database=znuny
      - APP_DatabaseUser=znuny
      - APP_DatabasePw=znuny
      - APP_NodeID={{.Task.Slot}}
      - APP_LigeroSmart_Node=elasticsearch
      - APP_CustomerID=${PROJECT_NAME}
      - APP_FQDN=${WEBSERVER_FQDN}
      - APP_DefaultLanguage=pt_BR
      - TZ=America/Sao_Paulo
      - ROOT_PASSWORD=${ROOT_PASSWORD:-ligero}
      - DEBUG_MODE=1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      placement:
        constraints:
          - node.labels.webserver == true
      #resources:
      #  limits:
      #    cpus: '1'
      #    memory: 3G
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.default.frontend.rule=PathPrefix:/
        #- traefik.user.frontend.rule=Path:/atendente;ReplacePath:/otrs/index.pl
        #- traefik.customer.frontend.rule=Path:/;ReplacePath:/otrs/customer.pl
        - traefik.protocol=http
        - traefik.docker.network=web
        - traefik.frontend.headers.customResponseHeaders=access-control-allow-origin:*
    networks:
      - web
      - default


  database:
    image: mariadb:10.3
    volumes:
      - mariadb-data:/var/lib/mysql
      #- mariadb-entrypoint:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=znuny
      - MYSQL_DATABASE=znuny
      - MYSQL_USER=znuny
      - MYSQL_PASSWORD=znuny
      - TZ=America/Sao_Paulo
    command:
      - --max-allowed-packet=64M
      - --innodb-log-file-size=256M
      - --innodb-buffer-pool-size=1G
      - --log-output=TABLE
      - --slow-query-log=1
      - --character-set-server=utf8
      - --bind-address=0.0.0.0
      - --innodb-use-native-aio=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      #resources:
      #  limits:
      #    cpus: '1'
      #    memory: 2G

  grafana:
    image: ligero/grafana:8
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_AUTH_BASIC_ENABLED=false # avoid elasticsearch auth
      - MYSQL_DATABASE=znuny
      - MYSQL_USER=znuny
      - MYSQL_PASSWORD=znuny
      - GF_INSTALL_PLUGINS=marcusolsson-gantt-panel
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/var/lib/grafana/ldap.toml
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default
      - web
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.grafana == true
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.frontend.rule=PathPrefixStrip:/grafana
        - traefik.protocol=http
        - traefik.docker.network=web
        - traefik.frontend.headers.customResponseHeaders=access-control-allow-origin:*
    
  elasticsearch:
    image: ligero/elasticsearch:6.8.23
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=znuny-cluster
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - default
      #- web
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.labels.elasticsearch == true
      #resources:
      #  limits:
      #    cpus: '1'
      #    memory: 2G
      #labels:
      #  - traefik.enable=true
      #  - traefik.port=9200
      #  - traefik.es-path.frontend.rule=PathPrefixStrip:/elasticsearch
      #  - traefik.es-path.frontend.auth.basic.users=${ELASTICSEARCH_AUTH_BASIC}
      #  - traefik.protocol=http

  ssh:
    image: ligero/ligerosmart:sshd
    volumes:
      - app-data:/opt/otrs
      - app-backups:/app-backups
    environment:
      - APP_DatabaseType=mysql
      - APP_DatabaseHost=database
      - APP_Database=znuny
      - APP_DatabaseUser=znuny
      - APP_DatabasePw=znuny
      - APP_NodeID={{.Task.Slot}}
      - APP_LigeroSmart_Node=elasticsearch
      - APP_CustomerID=${PROJECT_NAME}
      - APP_FQDN=${WEBSERVER_FQDN}
      - TZ=America/Sao_Paulo
      - START_SSHD=1
      - SSH_PASSWORD=aPWEos9srIq6c
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.webserver == true
      #resources:
      #  limits:
      #    cpus: '1'
      #    memory: 512M
    ports:
       - 2200:22

volumes:
  app-data:
    driver: local
  www-html:
    driver: local
  app-backups:
    driver: local
  mariadb-data:
    driver: local
  mariadb-entrypoint:
    driver: local
  grafana-data:
    driver: local
  elasticsearch-data:
    driver: local
      
networks:
  web:
    external: 
      name: web
